exclude: "^test-firefox-profile/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # HTML, CSS, TypeScript, Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        name: prettier (Markdown)
        types: [file]
        file: \.md$
      - id: prettier
        name: prettier (HTML & CSS)
        types: [file]
        file: \.(html|css)$
      - id: prettier
        name: prettier (TypeScript)
        types: [file]
        file: \.(ts|tsx)$
